//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tt195361.Casl2Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tt195361.Casl2Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} の値 {1} が {2} の値 {3} より小さいです。{0} の値は {2} の値より大きいか、等しくなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ArgGreaterEqual {
            get {
                return ResourceManager.GetString("MSG_ArgGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} として指定の値 {1} は、{2} ~ {3} の範囲外です。範囲内の値を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ArgRangeError {
            get {
                return ResourceManager.GetString("MSG_ArgRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} クラスのオブジェクトの作成には 1 つ以上の項目が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_AtLeastOneItemForTheClass {
            get {
                return ResourceManager.GetString("MSG_AtLeastOneItemForTheClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のレジスタ {0} は指標レジスタとして使えません。指標レジスタとして用いる GR は、記号 GR{1}～GR{2} で指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CanNotBeIndexRegister {
            get {
                return ResourceManager.GetString("MSG_CanNotBeIndexRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字 &apos;{0}&apos; は JIS X 0201 で表せません。JIS X 0201 で表せる文字を使ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CanNotRepresentInJisx0201 {
            get {
                return ResourceManager.GetString("MSG_CanNotRepresentInJisx0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を定数として解釈できませんでした。10 進定数 (n)、16 進定数 (#h)、文字定数 (&apos;文字列&apos;)、アドレス定数 (ラベル) のいずれかを記述してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ConstantParseError {
            get {
                return ResourceManager.GetString("MSG_ConstantParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   語のコレクションに語を追加できませんでした。語のコレクションの最大サイズ {0} を超える語を追加しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CouldNotAddToWordCollection {
            get {
                return ResourceManager.GetString("MSG_CouldNotAddToWordCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行開始番地を指定するラベル &quot;{0}&quot; の定義を取得できませんでした。詳細は InnerException を参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CouldNotGetExecStartLabelDefinition {
            get {
                return ResourceManager.GetString("MSG_CouldNotGetExecStartLabelDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リテラルで使用する DC 命令のラベルを作成できませんでした。&quot;{0}&quot; で始まる名前のラベルを減らしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CouldNotMakeLiteralLabel {
            get {
                return ResourceManager.GetString("MSG_CouldNotMakeLiteralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   字句要素 {0} をアドレスとして解釈できませんでした。アドレスは、10 進定数、16 進定数、アドレス定数又はリテラルで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CouldNotParseAsAdr {
            get {
                return ResourceManager.GetString("MSG_CouldNotParseAsAdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字 &apos;{0}&apos; で始まる句ををオペランドの字句要素として解釈できませんでした。オペランドの字句要素には、10 進定数 (n)、16 進定数 (#h)、文字定数 (&apos;文字列&apos;)、アドレス定数 (ラベル)、レジスタ名 (GRn)、リテラル (=定数) があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CouldNotParseAsToken {
            get {
                return ResourceManager.GetString("MSG_CouldNotParseAsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドレス #{0:x04} の命令 #{1:x04} の実行でエラーが発生しました。詳細は InnerException を参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CpuExecutionError {
            get {
                return ResourceManager.GetString("MSG_CpuExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入口名 &quot;{0}&quot; はすでに定義されています。入口名はすべてのプログラムの中で一意にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_EntryNameAlreadyDefined {
            get {
                return ResourceManager.GetString("MSG_EntryNameAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オペランド &quot;r1,r2&quot; 又は &quot;r,adr[,x]&quot; で、r2 あるいは adr を解釈できませんでした。レジスタ名かアドレスを指定してください。詳細は InnerException を参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_FailedToParseR2OrAdrX {
            get {
                return ResourceManager.GetString("MSG_FailedToParseR2OrAdrX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   END 命令の後に命令が書かれています。END 命令の後には命令を書かないでください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_InstructionAfterEnd {
            get {
                return ResourceManager.GetString("MSG_InstructionAfterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の命令コード &quot;{0}&quot; は定義されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_InstructionNotDefined {
            get {
                return ResourceManager.GetString("MSG_InstructionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の文字 &apos;{0}&apos; は 10 進定数を記述する半角数字 (0~9) ではありません。10 進定数には半角数字を使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_InvalidCharForDecimalConstant {
            get {
                return ResourceManager.GetString("MSG_InvalidCharForDecimalConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16 進定数として指定の文字列 &quot;{0}&quot; の桁数が {1} 桁ではなく {2} 桁です。16 進定数は #h の形式で、h は {1} 桁の 16 進数 (0~9, A~F) で指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_InvalidHexConstantDigitCount {
            get {
                return ResourceManager.GetString("MSG_InvalidHexConstantDigitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル &quot;{0}&quot; はすでに定義されています。ラベルの名前は一つのプログラムの中で一意にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LabelAlreadyDefined {
            get {
                return ResourceManager.GetString("MSG_LabelAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル &quot;{0}&quot; の先頭の文字 &apos;{1}&apos; が半角英大文字ではありません。ラベルの先頭の文字は半角英大文字にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LabelFirstCharIsNotUppercase {
            get {
                return ResourceManager.GetString("MSG_LabelFirstCharIsNotUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル &quot;{0}&quot; は予約語です。ラベルには予約語を使わないでください。予約語は {1} です。  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LabelIsReservedWord {
            get {
                return ResourceManager.GetString("MSG_LabelIsReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル &quot;{0}&quot; の長さ {1} 文字は有効な範囲外です。ラベルの長さは {2} ~ {3} 文字にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LabelLengthOutOfRange {
            get {
                return ResourceManager.GetString("MSG_LabelLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定義されていないラベル &quot;{0}&quot; を参照しています。指定のラベルを定義してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LabelNotDefined {
            get {
                return ResourceManager.GetString("MSG_LabelNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル &quot;{0}&quot; がプログラム内でも他のプログラムの入口名としても定義されていません。プログラム内あるいは他のプログラムの入口名として定義してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LabelOrEntryNameNotDefined {
            get {
                return ResourceManager.GetString("MSG_LabelOrEntryNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル &quot;{0}&quot; の文字 &apos;{1}&apos; が、半角英大文字でも半角数字でもありません。ラベルの 2 文字目以降は、半角英大文字または半角数字にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LabelSubsequentCharIsNeitherUppercaseNorDigit {
            get {
                return ResourceManager.GetString("MSG_LabelSubsequentCharIsNeitherUppercaseNorDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} をリテラルとして解釈できませんでした。リテラルは、10 進定数、16 進定数、または文字定数の前に等号 (=) を付けて記述します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_LiteralParseError {
            get {
                return ResourceManager.GetString("MSG_LiteralParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリアドレスの値 {0} (= {1} ({2}) + {3} ({4}) が COMET II 主記憶のアドレス範囲 {5} ~ {6} に入りません。プログラムを小さくするなど、主記憶に入るようにしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_MemoryAddressOutOfRange {
            get {
                return ResourceManager.GetString("MSG_MemoryAddressOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムに 2 つ以上の END 命令があります。END 命令は 1 つだけ指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_MoreThanOneEndInstruction {
            get {
                return ResourceManager.GetString("MSG_MoreThanOneEndInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムに 2 つ以上の START 命令があります。START 命令は 1 つだけ指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_MoreThanOneStartInstruction {
            get {
                return ResourceManager.GetString("MSG_MoreThanOneStartInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の文字定数 &quot;{0}&quot; で、閉じ側のアポストロフィ (&apos;) がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NoCloseQuoteInStrConstant {
            get {
                return ResourceManager.GetString("MSG_NoCloseQuoteInStrConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムに END 命令がありません。プログラムには END 命令を 1 つ指定し、プログラムの終わりを定義してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NoEndInstruction {
            get {
                return ResourceManager.GetString("MSG_NoEndInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   命令コードがありません。命令行には、オプションのラベルと空白に続いて、命令コードがなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NoInstructionInInstructionLine {
            get {
                return ResourceManager.GetString("MSG_NoInstructionInInstructionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベルを予期していましたが指定されていませんでした。ラベルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NoLabel {
            get {
                return ResourceManager.GetString("MSG_NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START 命令にラベルがありません。START 命令のラベルは、他のプログラムから入口名として参照します。ラベルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NoLabelForStart {
            get {
                return ResourceManager.GetString("MSG_NoLabelForStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムに START 命令がありません。プログラムには START 命令を 1 つ指定し、プログラムの先頭を定義してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NoStartInstruction {
            get {
                return ResourceManager.GetString("MSG_NoStartInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次の文字として &apos;{0}&apos; を予期していましたが、実際の文字は &apos;{1}&apos; でした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NotExpectedChar {
            get {
                return ResourceManager.GetString("MSG_NotExpectedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オペランドの字句要素として {0} を予期していましたが、実際は {1} でした。{0} を記述してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NotExpectedToken {
            get {
                return ResourceManager.GetString("MSG_NotExpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 命令のオペランド &quot;{1}&quot; で &quot;{2}&quot; が解釈できずに残りました。記述形式を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_NotParsedStringRemainsInOperand {
            get {
                return ResourceManager.GetString("MSG_NotParsedStringRemainsInOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のオブジェクト {0} の値が null です。{0} には null でない値を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ObjectIsNull {
            get {
                return ResourceManager.GetString("MSG_ObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オペランドを r,adr[,x] としても r1,r2 としても解釈できませんでした。オペランドに r,adr[,x] あるいは r1,r2 を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_OperandNeitherRAdrXNorR1R2 {
            get {
                return ResourceManager.GetString("MSG_OperandNeitherRAdrXNorR1R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 命令のオペランドの解釈で問題が発生しました。オペランドの記述形式は {1} です。確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_OperandParseError {
            get {
                return ResourceManager.GetString("MSG_OperandParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} をラベルとして解釈できませんでした。オペランドは、空にするか、ラベルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_OptionLabelParseError {
            get {
                return ResourceManager.GetString("MSG_OptionLabelParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定義されていないラベル &quot;{0}&quot; のオフセットを登録しようとしています。プログラムになにか問題があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_RegisteringOffsetForNotDefinedLabel {
            get {
                return ResourceManager.GetString("MSG_RegisteringOffsetForNotDefinedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START 命令のオペランドに指定した実行開始番地のラベル &quot;{0}&quot; が定義されていません。ラベルを定義してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_StartLabelNotDefined {
            get {
                return ResourceManager.GetString("MSG_StartLabelNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   命令コード 0x{0:x02} は未定義です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_UndefinedOpcode {
            get {
                return ResourceManager.GetString("MSG_UndefinedOpcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の文字列 &quot;{0}&quot; はレジスタ名ではありません。レジスタ名は、記号 {1}~{2} で指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_UndefinedRegisterName {
            get {
                return ResourceManager.GetString("MSG_UndefinedRegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   語数に指定の値 {0} は有効範囲外です。有効範囲 {1} &lt;= 語数 &lt;= {2} の値を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_WordCountOutOfRange {
            get {
                return ResourceManager.GetString("MSG_WordCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列定数の文字数が 0 です。文字列定数には 1 文字以上の文字を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ZeroCharsInStringConstant {
            get {
                return ResourceManager.GetString("MSG_ZeroCharsInStringConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10 進定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_DecimalConstant {
            get {
                return ResourceManager.GetString("STR_DecimalConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列の終わり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_EndOfStr {
            get {
                return ResourceManager.GetString("STR_EndOfStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オペランドの終わり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_EndOfToken {
            get {
                return ResourceManager.GetString("STR_EndOfToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16 進定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_HexaDecimalConstant {
            get {
                return ResourceManager.GetString("STR_HexaDecimalConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} のインデクサーの引数 {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_IndexerArgDscr {
            get {
                return ResourceManager.GetString("STR_IndexerArgDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_Label {
            get {
                return ResourceManager.GetString("STR_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レジスタ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_RegisterName {
            get {
                return ResourceManager.GetString("STR_RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STR_StringConstant {
            get {
                return ResourceManager.GetString("STR_StringConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adr[,x] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_AdrX {
            get {
                return ResourceManager.GetString("SYN_AdrX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;定数[,定数]...&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_ConstantList {
            get {
                return ResourceManager.GetString("SYN_ConstantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[実行開始番地]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_ExecStartAddr {
            get {
                return ResourceManager.GetString("SYN_ExecStartAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;入力領域,入力文字長領域&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_InputArea {
            get {
                return ResourceManager.GetString("SYN_InputArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オペランドなし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_NoOperand {
            get {
                return ResourceManager.GetString("SYN_NoOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;出力領域,出力文字長領域&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_OutputArea {
            get {
                return ResourceManager.GetString("SYN_OutputArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   r に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_R {
            get {
                return ResourceManager.GetString("SYN_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   r1,r2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_R1R2 {
            get {
                return ResourceManager.GetString("SYN_R1R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   r,adr[,x] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_RAdrX {
            get {
                return ResourceManager.GetString("SYN_RAdrX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   r,adr[,x] あるいは r1,r2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_RAdrXOrR1R2 {
            get {
                return ResourceManager.GetString("SYN_RAdrXOrR1R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   語数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYN_WordCount {
            get {
                return ResourceManager.GetString("SYN_WordCount", resourceCulture);
            }
        }
    }
}
